# Generated by Django 2.0.5 on 2018-05-16 05:56

from django.db import migrations, models
from bims.models.biological_collection_record import (
    collection_post_save_handler,
    collection_post_save_update_cluster
)


def move_habitat_value(apps, schema_editor):
    try:
        BioCollectionRecords = apps.get_model('bims',
                                              'BiologicalCollectionRecord')
        Fish = apps.get_model('fish', 'FishCollectionRecord')
    except LookupError:
        return
    models.signals.post_save.disconnect(
        collection_post_save_handler
    )
    models.signals.post_save.disconnect(
        collection_post_save_update_cluster
    )
    fishes = Fish.objects.filter(
        habitat__isnull=False
    )
    for fish in fishes:
        bio = BioCollectionRecords.objects.get(
            id=fish.id
        )
        bio.collection_habitat = fish.habitat
        bio.save()
    models.signals.post_save.connect(
        collection_post_save_handler
    )
    models.signals.post_save.connect(
        collection_post_save_update_cluster
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bims', '0086_biologicalcollectionrecord_collection_habitat'),
    ]

    operations = [
        migrations.RunPython(
            move_habitat_value
        ),
    ]
