# Generated by Django 2.0.2 on 2018-02-25 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FishCollectionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality_id', models.IntegerField(blank=True, null=True)),
                ('species', models.CharField(blank=True, default='', max_length=100)),
                ('habitat', models.CharField(blank=True, choices=[('euryhaline', 'Euryhaline'), ('freshwater', 'Freshwater')], max_length=50)),
                ('category', models.CharField(blank=True, choices=[('alien', 'Alien'), ('indigenouse', 'Indigenous'), ('translocated', 'Translocated')], max_length=50)),
                ('present', models.BooleanField(default=False)),
                ('collection_date', models.DateField(default=django.utils.timezone.now)),
                ('collector', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LocationSite')),
            ],
        ),
        migrations.CreateModel(
            name='IucnStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('sensitive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbif_id', models.IntegerField(blank=True, null=True)),
                ('common_name', models.CharField(blank=True, default='', max_length=100)),
                ('scientific_name', models.CharField(blank=True, default='', max_length=100)),
                ('author', models.CharField(blank=True, default='', max_length=100)),
                ('iucn_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fish.IucnStatus')),
            ],
        ),
    ]
