# Generated by Django 2.0.3 on 2018-03-15 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0006_auto_20180313_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='iucn_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fish.IUCNStatus'),
        ),
    ]
