# Generated by Django 2.0.3 on 2018-03-20 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0007_auto_20180317_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iucnstatus',
            name='name',
        ),
        migrations.RemoveField(
            model_name='iucnstatus',
            name='narrative',
        ),
        migrations.AddField(
            model_name='iucnstatus',
            name='category',
            field=models.CharField(blank=True, choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('EW', 'Extinct In The Wild'), ('EX', 'Extinct')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='iucn_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fish.IUCNStatus'),
        ),
    ]
