# Generated by Django 2.0.3 on 2018-03-20 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0008_auto_20180320_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='iucn_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fish.IUCNStatus'),
        ),
    ]
