# Generated by Django 2.0.3 on 2018-03-27 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0007_auto_20180315_1045'),
        ('fish', '0009_auto_20180320_0837'),
    ]

    operations = [
    ]
