# Generated by Django 2.0.3 on 2018-03-28 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0010_merge_20180327_0903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CsvDocument',
        ),
        migrations.RemoveField(
            model_name='taxon',
            name='iucn_status',
        ),
        migrations.AlterField(
            model_name='fishcollectionrecord',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_collection_records', to='base.LocationSite'),
        ),
        migrations.AlterField(
            model_name='fishcollectionrecord',
            name='taxon_gbif_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Taxon', verbose_name='Taxon GBIF '),
        ),
        migrations.DeleteModel(
            name='IucnStatus',
        ),
        migrations.DeleteModel(
            name='Taxon',
        ),
    ]
