# Generated by Django 2.0.4 on 2018-04-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0011_auto_20180328_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishcollectionrecord',
            name='absent',
            field=models.BooleanField(default=True),
        ),
    ]
