# Generated by Django 2.0.2 on 2018-02-28 04:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geometry_point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('geometry_line', django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326)),
                ('geometry_polygon', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
                ('geometry_multipolygon', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='locationsite',
            name='location_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LocationType'),
        ),
    ]
