# Generated by Django 2.0.2 on 2018-02-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationtype',
            options={'ordering': ['name']},
        ),
    ]
