# Generated by Django 2.0.2 on 2018-02-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180228_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationTypeAllowedGeometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_geometry', models.CharField(choices=[('POINT', 'Point'), ('LINE', 'Line'), ('POLYGON', 'Polygon'), ('MULTIPOLYGON', 'Multipolygon')], max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='locationtype',
            name='allowed_geometry',
            field=models.ManyToManyField(to='base.LocationTypeAllowedGeometry'),
        ),
    ]
