# Generated by Django 2.0.3 on 2018-03-28 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_csvdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='IUCNStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('EW', 'Extinct In The Wild'), ('EX', 'Extinct')], default='', max_length=50)),
                ('sensitive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'IUCN Status',
                'verbose_name_plural': 'IUCN Status',
            },
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbif_id', models.IntegerField(blank=True, null=True, verbose_name='GBIF id')),
                ('common_name', models.CharField(blank=True, default='', max_length=100)),
                ('scientific_name', models.CharField(blank=True, default='', max_length=100)),
                ('author', models.CharField(blank=True, default='', max_length=100)),
                ('iucn_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.IUCNStatus')),
            ],
            options={
                'verbose_name': 'Taxon',
                'verbose_name_plural': 'Taxa',
            },
        ),
    ]
