# Generated by Django 2.0.3 on 2018-03-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_survey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='site',
            new_name='sites',
        ),
    ]
