# Generated by Django 2.0.3 on 2018-04-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20180329_0512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVDocument',
        ),
    ]
